name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: presbyopia-vision-test-apk
          path: build/app/outputs/flutter-apk/app-release.apkwith:
          name: presbyopia-vision-test-apk
          path: build/app/outputs/flutter-apk/app-release.apk
